// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Connection struct
 */
export class Connection {
    "id": string;
    "name": string;
    "host": string;
    "port": number;
    "username": string;
    "password"?: string;
    "authMethod": string;
    "privateKey"?: string;
    "passphrase"?: string;

    /**
     * 服务器分组，空=未分组
     */
    "group"?: string;
    "os"?: string;

    /**
     * ponytail: 非空时用 Credential 认证，忽略内联字段
     */
    "credentialId"?: string;
    "terminalInitPath"?: string;
    "fileManagerInitPath"?: string;
    "terminalEncoding"?: string;
    "allowLegacySshRsa"?: boolean;

    /**
     * AutoReconnect 自动重连(按服务器粒度,默认关):传输/保活断开后前端自动重连该会话。
     */
    "autoReconnect"?: boolean;
    "proxyMode"?: string;
    "proxyNodeId"?: string;
    "proxyType"?: string;
    "proxyHost"?: string;
    "proxyPort"?: number;
    "proxyUsername"?: string;
    "proxyPassword"?: string;

    /**
     * Unix 毫秒时间戳，合并时判断新旧
     */
    "last_modified"?: number;

    /** Creates a new Connection instance. */
    constructor($$source: Partial<Connection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("authMethod" in $$source)) {
            this["authMethod"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     */
    static createFrom($$source: any = {}): Connection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Connection($$parsedSource as Partial<Connection>);
    }
}

/**
 * Credential 可复用的认证凭据，多个 Connection 可引用同一 Credential
 */
export class Credential {
    "id": string;
    "name": string;

    /**
     * "password" | "privateKey"
     */
    "authMethod": string;
    "username": string;

    /**
     * 加密存储
     */
    "password"?: string;

    /**
     * 加密存储
     */
    "privateKey"?: string;

    /**
     * 加密存储
     */
    "passphrase"?: string;

    /**
     * Unix 毫秒时间戳
     */
    "last_modified"?: number;

    /** Creates a new Credential instance. */
    constructor($$source: Partial<Credential> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("authMethod" in $$source)) {
            this["authMethod"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Credential instance from a string or object.
     */
    static createFrom($$source: any = {}): Credential {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Credential($$parsedSource as Partial<Credential>);
    }
}

export class FTPCertificateInfo {
    "endpoint": string;
    "fingerprint": string;
    "pinnedFingerprint"?: string;
    "subject": string;
    "issuer": string;
    "serialNumber": string;
    "dnsNames": string[];
    "ipAddresses": string[];
    "notBefore": string;
    "notAfter": string;

    /** Creates a new FTPCertificateInfo instance. */
    constructor($$source: Partial<FTPCertificateInfo> = {}) {
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("fingerprint" in $$source)) {
            this["fingerprint"] = "";
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("issuer" in $$source)) {
            this["issuer"] = "";
        }
        if (!("serialNumber" in $$source)) {
            this["serialNumber"] = "";
        }
        if (!("dnsNames" in $$source)) {
            this["dnsNames"] = [];
        }
        if (!("ipAddresses" in $$source)) {
            this["ipAddresses"] = [];
        }
        if (!("notBefore" in $$source)) {
            this["notBefore"] = "";
        }
        if (!("notAfter" in $$source)) {
            this["notAfter"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FTPCertificateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FTPCertificateInfo {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dnsNames" in $$parsedSource) {
            $$parsedSource["dnsNames"] = $$createField6_0($$parsedSource["dnsNames"]);
        }
        if ("ipAddresses" in $$parsedSource) {
            $$parsedSource["ipAddresses"] = $$createField7_0($$parsedSource["ipAddresses"]);
        }
        return new FTPCertificateInfo($$parsedSource as Partial<FTPCertificateInfo>);
    }
}

export class FTPConnectionTestResult {
    "success": boolean;
    "certificateApprovalRequired"?: FTPCertificateInfo | null;

    /** Creates a new FTPConnectionTestResult instance. */
    constructor($$source: Partial<FTPConnectionTestResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FTPConnectionTestResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FTPConnectionTestResult {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("certificateApprovalRequired" in $$parsedSource) {
            $$parsedSource["certificateApprovalRequired"] = $$createField1_0($$parsedSource["certificateApprovalRequired"]);
        }
        return new FTPConnectionTestResult($$parsedSource as Partial<FTPConnectionTestResult>);
    }
}

/**
 * ImportResult 导入操作的统计结果
 */
export class ImportResult {
    /**
     * 文件中的节点总数
     */
    "total": number;

    /**
     * 实际新增数
     */
    "imported": number;

    /**
     * 跳过的重复数
     */
    "skipped": number;

    /**
     * 被跳过的节点明细
     */
    "details": skippedItem[];

    /** Creates a new ImportResult instance. */
    constructor($$source: Partial<ImportResult> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("imported" in $$source)) {
            this["imported"] = 0;
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }
        if (!("details" in $$source)) {
            this["details"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportResult {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField3_0($$parsedSource["details"]);
        }
        return new ImportResult($$parsedSource as Partial<ImportResult>);
    }
}

export class SFTPConnectionTestResult {
    "success": boolean;
    "hostKeyMismatch"?: SFTPHostKeyMismatch | null;

    /** Creates a new SFTPConnectionTestResult instance. */
    constructor($$source: Partial<SFTPConnectionTestResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SFTPConnectionTestResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SFTPConnectionTestResult {
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hostKeyMismatch" in $$parsedSource) {
            $$parsedSource["hostKeyMismatch"] = $$createField1_0($$parsedSource["hostKeyMismatch"]);
        }
        return new SFTPConnectionTestResult($$parsedSource as Partial<SFTPConnectionTestResult>);
    }
}

export class SFTPHostKeyMismatch {
    "hostname": string;
    "newFingerprint": string;
    "oldFingerprints": string[];
    "knownHostsPath": string;

    /** Creates a new SFTPHostKeyMismatch instance. */
    constructor($$source: Partial<SFTPHostKeyMismatch> = {}) {
        if (!("hostname" in $$source)) {
            this["hostname"] = "";
        }
        if (!("newFingerprint" in $$source)) {
            this["newFingerprint"] = "";
        }
        if (!("oldFingerprints" in $$source)) {
            this["oldFingerprints"] = [];
        }
        if (!("knownHostsPath" in $$source)) {
            this["knownHostsPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SFTPHostKeyMismatch instance from a string or object.
     */
    static createFrom($$source: any = {}): SFTPHostKeyMismatch {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("oldFingerprints" in $$parsedSource) {
            $$parsedSource["oldFingerprints"] = $$createField2_0($$parsedSource["oldFingerprints"]);
        }
        return new SFTPHostKeyMismatch($$parsedSource as Partial<SFTPHostKeyMismatch>);
    }
}

/**
 * SyncTombstonePruneResult 按天数清理墓碑的结果。
 */
export class SyncTombstonePruneResult {
    "removedConnections": number;
    "removedCredentials": number;
    "remainingConnections": number;
    "remainingCredentials": number;
    "uploaded": number;

    /** Creates a new SyncTombstonePruneResult instance. */
    constructor($$source: Partial<SyncTombstonePruneResult> = {}) {
        if (!("removedConnections" in $$source)) {
            this["removedConnections"] = 0;
        }
        if (!("removedCredentials" in $$source)) {
            this["removedCredentials"] = 0;
        }
        if (!("remainingConnections" in $$source)) {
            this["remainingConnections"] = 0;
        }
        if (!("remainingCredentials" in $$source)) {
            this["remainingCredentials"] = 0;
        }
        if (!("uploaded" in $$source)) {
            this["uploaded"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncTombstonePruneResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncTombstonePruneResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncTombstonePruneResult($$parsedSource as Partial<SyncTombstonePruneResult>);
    }
}

/**
 * SyncTombstoneStats 同步删除记录条数（供设置页展示）。
 */
export class SyncTombstoneStats {
    "connections": number;
    "credentials": number;

    /** Creates a new SyncTombstoneStats instance. */
    constructor($$source: Partial<SyncTombstoneStats> = {}) {
        if (!("connections" in $$source)) {
            this["connections"] = 0;
        }
        if (!("credentials" in $$source)) {
            this["credentials"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncTombstoneStats instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncTombstoneStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncTombstoneStats($$parsedSource as Partial<SyncTombstoneStats>);
    }
}

/**
 * TombstoneConflictItem 预检：本地墓碑会从目标云删掉的项。
 */
export class TombstoneConflictItem {
    "id": string;
    "name": string;
    "host"?: string;

    /** Creates a new TombstoneConflictItem instance. */
    constructor($$source: Partial<TombstoneConflictItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TombstoneConflictItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TombstoneConflictItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TombstoneConflictItem($$parsedSource as Partial<TombstoneConflictItem>);
    }
}

/**
 * TombstoneConflictPreview 合并同步前预检结果：先读远端再算「墓碑 ∩ 远端仍在」。
 */
export class TombstoneConflictPreview {
    "providers": string[];
    "wouldDeleteConnections": TombstoneConflictItem[];
    "wouldDeleteCredentials": TombstoneConflictItem[];

    /** Creates a new TombstoneConflictPreview instance. */
    constructor($$source: Partial<TombstoneConflictPreview> = {}) {
        if (!("providers" in $$source)) {
            this["providers"] = [];
        }
        if (!("wouldDeleteConnections" in $$source)) {
            this["wouldDeleteConnections"] = [];
        }
        if (!("wouldDeleteCredentials" in $$source)) {
            this["wouldDeleteCredentials"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TombstoneConflictPreview instance from a string or object.
     */
    static createFrom($$source: any = {}): TombstoneConflictPreview {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType8;
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField0_0($$parsedSource["providers"]);
        }
        if ("wouldDeleteConnections" in $$parsedSource) {
            $$parsedSource["wouldDeleteConnections"] = $$createField1_0($$parsedSource["wouldDeleteConnections"]);
        }
        if ("wouldDeleteCredentials" in $$parsedSource) {
            $$parsedSource["wouldDeleteCredentials"] = $$createField2_0($$parsedSource["wouldDeleteCredentials"]);
        }
        return new TombstoneConflictPreview($$parsedSource as Partial<TombstoneConflictPreview>);
    }
}

/**
 * skippedItem 记录导入时被跳过（本地已存在）的节点信息
 */
export class skippedItem {
    "name": string;
    "host": string;
    "port": number;
    "username": string;

    /** Creates a new skippedItem instance. */
    constructor($$source: Partial<skippedItem> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new skippedItem instance from a string or object.
     */
    static createFrom($$source: any = {}): skippedItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new skippedItem($$parsedSource as Partial<skippedItem>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = FTPCertificateInfo.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = skippedItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = SFTPHostKeyMismatch.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = TombstoneConflictItem.createFrom;
const $$createType8 = $Create.Array($$createType7);
