// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ResponsesPromptCacheFormatPolicy {
    "format": string;
    "durations": string[];

    /** Creates a new ResponsesPromptCacheFormatPolicy instance. */
    constructor($$source: Partial<ResponsesPromptCacheFormatPolicy> = {}) {
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("durations" in $$source)) {
            this["durations"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResponsesPromptCacheFormatPolicy instance from a string or object.
     */
    static createFrom($$source: any = {}): ResponsesPromptCacheFormatPolicy {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("durations" in $$parsedSource) {
            $$parsedSource["durations"] = $$createField1_0($$parsedSource["durations"]);
        }
        return new ResponsesPromptCacheFormatPolicy($$parsedSource as Partial<ResponsesPromptCacheFormatPolicy>);
    }
}

export class ResponsesPromptCachePolicy {
    "modelId": string;
    "known": boolean;
    "format"?: string;
    "supportedDurations": string[];
    "defaultDuration"?: string;
    "availableFormats": ResponsesPromptCacheFormatPolicy[];

    /** Creates a new ResponsesPromptCachePolicy instance. */
    constructor($$source: Partial<ResponsesPromptCachePolicy> = {}) {
        if (!("modelId" in $$source)) {
            this["modelId"] = "";
        }
        if (!("known" in $$source)) {
            this["known"] = false;
        }
        if (!("supportedDurations" in $$source)) {
            this["supportedDurations"] = [];
        }
        if (!("availableFormats" in $$source)) {
            this["availableFormats"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResponsesPromptCachePolicy instance from a string or object.
     */
    static createFrom($$source: any = {}): ResponsesPromptCachePolicy {
        const $$createField3_0 = $$createType0;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("supportedDurations" in $$parsedSource) {
            $$parsedSource["supportedDurations"] = $$createField3_0($$parsedSource["supportedDurations"]);
        }
        if ("availableFormats" in $$parsedSource) {
            $$parsedSource["availableFormats"] = $$createField5_0($$parsedSource["availableFormats"]);
        }
        return new ResponsesPromptCachePolicy($$parsedSource as Partial<ResponsesPromptCachePolicy>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ResponsesPromptCacheFormatPolicy.createFrom;
const $$createType2 = $Create.Array($$createType1);
