// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "../ai/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as aitypes$0 from "../aitypes/models.js";

export function GetAIProviderState(): $CancellablePromise<ai$0.AIProviderState> {
    return $Call.ByID(418698785).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveAIProviderState(jsonStr: string): $CancellablePromise<void> {
    return $Call.ByID(2649888408, jsonStr);
}

// Private type creation functions
const $$createType0 = aitypes$0.AIProviderState.createFrom;
