// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GitHubContributor {
    "author": GitHubContributorAuthor;
    "total": number;
    "weeks": GitHubContributorWeek[];

    /** Creates a new GitHubContributor instance. */
    constructor($$source: Partial<GitHubContributor> = {}) {
        if (!("author" in $$source)) {
            this["author"] = (new GitHubContributorAuthor());
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("weeks" in $$source)) {
            this["weeks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubContributor instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubContributor {
        const $$createField0_0 = $$createType0;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField0_0($$parsedSource["author"]);
        }
        if ("weeks" in $$parsedSource) {
            $$parsedSource["weeks"] = $$createField2_0($$parsedSource["weeks"]);
        }
        return new GitHubContributor($$parsedSource as Partial<GitHubContributor>);
    }
}

export class GitHubContributorAuthor {
    "login": string;
    "avatar": string;
    "path": string;

    /** Creates a new GitHubContributorAuthor instance. */
    constructor($$source: Partial<GitHubContributorAuthor> = {}) {
        if (!("login" in $$source)) {
            this["login"] = "";
        }
        if (!("avatar" in $$source)) {
            this["avatar"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubContributorAuthor instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubContributorAuthor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitHubContributorAuthor($$parsedSource as Partial<GitHubContributorAuthor>);
    }
}

export class GitHubContributorWeek {
    "w": number;
    "a": number;
    "d": number;
    "c": number;

    /** Creates a new GitHubContributorWeek instance. */
    constructor($$source: Partial<GitHubContributorWeek> = {}) {
        if (!("w" in $$source)) {
            this["w"] = 0;
        }
        if (!("a" in $$source)) {
            this["a"] = 0;
        }
        if (!("d" in $$source)) {
            this["d"] = 0;
        }
        if (!("c" in $$source)) {
            this["c"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubContributorWeek instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubContributorWeek {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitHubContributorWeek($$parsedSource as Partial<GitHubContributorWeek>);
    }
}

// Private type creation functions
const $$createType0 = GitHubContributorAuthor.createFrom;
const $$createType1 = GitHubContributorWeek.createFrom;
const $$createType2 = $Create.Array($$createType1);
