// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AIChatCommandTerminalCandidate {
    "sessionId": string;
    "busy": boolean;
    "cwd": string;
    "current": boolean;
    "recommended": boolean;

    /** Creates a new AIChatCommandTerminalCandidate instance. */
    constructor($$source: Partial<AIChatCommandTerminalCandidate> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("busy" in $$source)) {
            this["busy"] = false;
        }
        if (!("cwd" in $$source)) {
            this["cwd"] = "";
        }
        if (!("current" in $$source)) {
            this["current"] = false;
        }
        if (!("recommended" in $$source)) {
            this["recommended"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIChatCommandTerminalCandidate instance from a string or object.
     */
    static createFrom($$source: any = {}): AIChatCommandTerminalCandidate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIChatCommandTerminalCandidate($$parsedSource as Partial<AIChatCommandTerminalCandidate>);
    }
}

export class AICollaborationPromptPreset {
    "id": string;
    "title": string;
    "text": string;

    /** Creates a new AICollaborationPromptPreset instance. */
    constructor($$source: Partial<AICollaborationPromptPreset> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AICollaborationPromptPreset instance from a string or object.
     */
    static createFrom($$source: any = {}): AICollaborationPromptPreset {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AICollaborationPromptPreset($$parsedSource as Partial<AICollaborationPromptPreset>);
    }
}

export class AIGlobalSettings {
    "currentProviderId": string;
    "autoApprovalEnabled": boolean;
    "alwaysAllowReadOnly": boolean;
    "alwaysAllowReadOnlyOutsideWorkspace": boolean;
    "alwaysAllowWrite": boolean;
    "alwaysAllowWriteOutsideWorkspace": boolean;
    "alwaysAllowWriteProtected": boolean;
    "alwaysAllowExecute": boolean;
    "executeApprovalMode": string;
    "allowedCommands"?: string[];
    "deniedCommands"?: string[];
    "slashCommands"?: AISlashCommand[];
    "collaborationPromptPresets"?: AICollaborationPromptPreset[];
    "systemPromptPresets"?: AISystemPromptPreset[];
    "collaborationExtraPrompt"?: string;
    "alwaysAllowMcp": boolean;
    "alwaysAllowModeSwitch": boolean;
    "alwaysAllowSubtasks": boolean;
    "alwaysAllowFollowupQuestions": boolean;
    "soundEnabled": boolean;
    "soundVolume"?: number;
    "mcpEnabled": boolean;
    "mcpAllowBrowserCalls": boolean;
    "mcpRequireApproval": boolean;
    "mcpActivityVisible": boolean;
    "terminalIsolation": boolean;
    "confirmDelete": boolean;
    "continueAfterToolRejection": boolean;
    "conversationAutoBackupEnabled": boolean;
    "conversationAutoBackupRetentionCount"?: number;
    "messageNavEnabled": boolean;
    "aiWorkspaceTabNumbersOnly": boolean;
    "approvalButtonOrder": string;
    "commandActionButtonOrder": string;
    "toolResultTokenThreshold"?: number;
    "aiRequestProxyId"?: string;
    "updatedAt"?: number;
    "proxyNodes"?: AIProxyNode[];
    "autoCondenseEnabled": boolean;
    "autoCondenseThresholdRatio"?: number;

    /**
     * AIDebugLogEnabled 控制是否把每轮 AI 请求与原始响应流写入 ai.log。
     * 旧配置缺少该键时,LoadAIGlobalSettings 会保留默认值(true),即默认开启。
     */
    "aiDebugLogEnabled": boolean;

    /** Creates a new AIGlobalSettings instance. */
    constructor($$source: Partial<AIGlobalSettings> = {}) {
        if (!("currentProviderId" in $$source)) {
            this["currentProviderId"] = "";
        }
        if (!("autoApprovalEnabled" in $$source)) {
            this["autoApprovalEnabled"] = false;
        }
        if (!("alwaysAllowReadOnly" in $$source)) {
            this["alwaysAllowReadOnly"] = false;
        }
        if (!("alwaysAllowReadOnlyOutsideWorkspace" in $$source)) {
            this["alwaysAllowReadOnlyOutsideWorkspace"] = false;
        }
        if (!("alwaysAllowWrite" in $$source)) {
            this["alwaysAllowWrite"] = false;
        }
        if (!("alwaysAllowWriteOutsideWorkspace" in $$source)) {
            this["alwaysAllowWriteOutsideWorkspace"] = false;
        }
        if (!("alwaysAllowWriteProtected" in $$source)) {
            this["alwaysAllowWriteProtected"] = false;
        }
        if (!("alwaysAllowExecute" in $$source)) {
            this["alwaysAllowExecute"] = false;
        }
        if (!("executeApprovalMode" in $$source)) {
            this["executeApprovalMode"] = "";
        }
        if (!("alwaysAllowMcp" in $$source)) {
            this["alwaysAllowMcp"] = false;
        }
        if (!("alwaysAllowModeSwitch" in $$source)) {
            this["alwaysAllowModeSwitch"] = false;
        }
        if (!("alwaysAllowSubtasks" in $$source)) {
            this["alwaysAllowSubtasks"] = false;
        }
        if (!("alwaysAllowFollowupQuestions" in $$source)) {
            this["alwaysAllowFollowupQuestions"] = false;
        }
        if (!("soundEnabled" in $$source)) {
            this["soundEnabled"] = false;
        }
        if (!("mcpEnabled" in $$source)) {
            this["mcpEnabled"] = false;
        }
        if (!("mcpAllowBrowserCalls" in $$source)) {
            this["mcpAllowBrowserCalls"] = false;
        }
        if (!("mcpRequireApproval" in $$source)) {
            this["mcpRequireApproval"] = false;
        }
        if (!("mcpActivityVisible" in $$source)) {
            this["mcpActivityVisible"] = false;
        }
        if (!("terminalIsolation" in $$source)) {
            this["terminalIsolation"] = false;
        }
        if (!("confirmDelete" in $$source)) {
            this["confirmDelete"] = false;
        }
        if (!("continueAfterToolRejection" in $$source)) {
            this["continueAfterToolRejection"] = false;
        }
        if (!("conversationAutoBackupEnabled" in $$source)) {
            this["conversationAutoBackupEnabled"] = false;
        }
        if (!("messageNavEnabled" in $$source)) {
            this["messageNavEnabled"] = false;
        }
        if (!("aiWorkspaceTabNumbersOnly" in $$source)) {
            this["aiWorkspaceTabNumbersOnly"] = false;
        }
        if (!("approvalButtonOrder" in $$source)) {
            this["approvalButtonOrder"] = "";
        }
        if (!("commandActionButtonOrder" in $$source)) {
            this["commandActionButtonOrder"] = "";
        }
        if (!("autoCondenseEnabled" in $$source)) {
            this["autoCondenseEnabled"] = false;
        }
        if (!("aiDebugLogEnabled" in $$source)) {
            this["aiDebugLogEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIGlobalSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AIGlobalSettings {
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType2;
        const $$createField12_0 = $$createType4;
        const $$createField13_0 = $$createType6;
        const $$createField37_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowedCommands" in $$parsedSource) {
            $$parsedSource["allowedCommands"] = $$createField9_0($$parsedSource["allowedCommands"]);
        }
        if ("deniedCommands" in $$parsedSource) {
            $$parsedSource["deniedCommands"] = $$createField10_0($$parsedSource["deniedCommands"]);
        }
        if ("slashCommands" in $$parsedSource) {
            $$parsedSource["slashCommands"] = $$createField11_0($$parsedSource["slashCommands"]);
        }
        if ("collaborationPromptPresets" in $$parsedSource) {
            $$parsedSource["collaborationPromptPresets"] = $$createField12_0($$parsedSource["collaborationPromptPresets"]);
        }
        if ("systemPromptPresets" in $$parsedSource) {
            $$parsedSource["systemPromptPresets"] = $$createField13_0($$parsedSource["systemPromptPresets"]);
        }
        if ("proxyNodes" in $$parsedSource) {
            $$parsedSource["proxyNodes"] = $$createField37_0($$parsedSource["proxyNodes"]);
        }
        return new AIGlobalSettings($$parsedSource as Partial<AIGlobalSettings>);
    }
}

export class AIProviderCustomHeader {
    "name": string;
    "value": string;

    /** Creates a new AIProviderCustomHeader instance. */
    constructor($$source: Partial<AIProviderCustomHeader> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProviderCustomHeader instance from a string or object.
     */
    static createFrom($$source: any = {}): AIProviderCustomHeader {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIProviderCustomHeader($$parsedSource as Partial<AIProviderCustomHeader>);
    }
}

export class AIProviderProfile {
    "id": string;
    "name": string;
    "provider": string;
    "model": string;
    "baseUrl": string;
    "apiKey": string;
    "customHeaders"?: AIProviderCustomHeader[];
    "modelTemperature"?: number | null;
    "modelTopP"?: number | null;
    "cacheStrategy": string;
    "openAiResponsesUsePromptCacheRetention": boolean;
    "openAiResponsesFinishOnCompletedEvent": boolean;
    "webSearchEnabled": boolean;
    "dedicatedWebSearchEnabled": boolean;
    "dedicatedWebSearchProviderId"?: string;
    "dedicatedProxyEnabled": boolean;
    "dedicatedProxyId"?: string;
    "reasoningEffort": string;
    "enableReasoningEffort": boolean;
    "openAiLegacyReasoningFormatEnabled": boolean;
    "systemPromptAppend"?: string;
    "systemPromptPresetId"?: string;
    "modelMaxTokens"?: number;
    "modelMaxThinkingTokens"?: number;
    "pinned": boolean;
    "updatedAt"?: number;

    /** Creates a new AIProviderProfile instance. */
    constructor($$source: Partial<AIProviderProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("cacheStrategy" in $$source)) {
            this["cacheStrategy"] = "";
        }
        if (!("openAiResponsesUsePromptCacheRetention" in $$source)) {
            this["openAiResponsesUsePromptCacheRetention"] = false;
        }
        if (!("openAiResponsesFinishOnCompletedEvent" in $$source)) {
            this["openAiResponsesFinishOnCompletedEvent"] = false;
        }
        if (!("webSearchEnabled" in $$source)) {
            this["webSearchEnabled"] = false;
        }
        if (!("dedicatedWebSearchEnabled" in $$source)) {
            this["dedicatedWebSearchEnabled"] = false;
        }
        if (!("dedicatedProxyEnabled" in $$source)) {
            this["dedicatedProxyEnabled"] = false;
        }
        if (!("reasoningEffort" in $$source)) {
            this["reasoningEffort"] = "";
        }
        if (!("enableReasoningEffort" in $$source)) {
            this["enableReasoningEffort"] = false;
        }
        if (!("openAiLegacyReasoningFormatEnabled" in $$source)) {
            this["openAiLegacyReasoningFormatEnabled"] = false;
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProviderProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): AIProviderProfile {
        const $$createField6_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("customHeaders" in $$parsedSource) {
            $$parsedSource["customHeaders"] = $$createField6_0($$parsedSource["customHeaders"]);
        }
        return new AIProviderProfile($$parsedSource as Partial<AIProviderProfile>);
    }
}

export class AIProviderState {
    "currentProviderId": string;
    "providers": AIProviderProfile[];

    /** Creates a new AIProviderState instance. */
    constructor($$source: Partial<AIProviderState> = {}) {
        if (!("currentProviderId" in $$source)) {
            this["currentProviderId"] = "";
        }
        if (!("providers" in $$source)) {
            this["providers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProviderState instance from a string or object.
     */
    static createFrom($$source: any = {}): AIProviderState {
        const $$createField1_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField1_0($$parsedSource["providers"]);
        }
        return new AIProviderState($$parsedSource as Partial<AIProviderState>);
    }
}

export class AIProxyNode {
    "id": string;
    "name": string;
    "type": string;
    "host": string;
    "port": number;
    "username"?: string;
    "password"?: string;
    "updatedAt"?: number;

    /** Creates a new AIProxyNode instance. */
    constructor($$source: Partial<AIProxyNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProxyNode instance from a string or object.
     */
    static createFrom($$source: any = {}): AIProxyNode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIProxyNode($$parsedSource as Partial<AIProxyNode>);
    }
}

export class AISlashCommand {
    "name": string;
    "prompt": string;

    /** Creates a new AISlashCommand instance. */
    constructor($$source: Partial<AISlashCommand> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AISlashCommand instance from a string or object.
     */
    static createFrom($$source: any = {}): AISlashCommand {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AISlashCommand($$parsedSource as Partial<AISlashCommand>);
    }
}

export class AISystemPromptPreset {
    "id": string;
    "title": string;
    "text": string;

    /** Creates a new AISystemPromptPreset instance. */
    constructor($$source: Partial<AISystemPromptPreset> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AISystemPromptPreset instance from a string or object.
     */
    static createFrom($$source: any = {}): AISystemPromptPreset {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AISystemPromptPreset($$parsedSource as Partial<AISystemPromptPreset>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = AISlashCommand.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = AICollaborationPromptPreset.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = AISystemPromptPreset.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = AIProxyNode.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = AIProviderCustomHeader.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = AIProviderProfile.createFrom;
const $$createType12 = $Create.Array($$createType11);
