// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class OwnershipCandidateEntry {
    "id": string;
    "name": string;

    /** Creates a new OwnershipCandidateEntry instance. */
    constructor($$source: Partial<OwnershipCandidateEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OwnershipCandidateEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): OwnershipCandidateEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OwnershipCandidateEntry($$parsedSource as Partial<OwnershipCandidateEntry>);
    }
}

export class OwnershipCandidates {
    "users": OwnershipCandidateEntry[];
    "groups": OwnershipCandidateEntry[];

    /** Creates a new OwnershipCandidates instance. */
    constructor($$source: Partial<OwnershipCandidates> = {}) {
        if (!("users" in $$source)) {
            this["users"] = [];
        }
        if (!("groups" in $$source)) {
            this["groups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OwnershipCandidates instance from a string or object.
     */
    static createFrom($$source: any = {}): OwnershipCandidates {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("users" in $$parsedSource) {
            $$parsedSource["users"] = $$createField0_0($$parsedSource["users"]);
        }
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField1_0($$parsedSource["groups"]);
        }
        return new OwnershipCandidates($$parsedSource as Partial<OwnershipCandidates>);
    }
}

export class PathOwnershipInfo {
    "uid": string;
    "gid": string;
    "mode": string;
    "permission": string;

    /** Creates a new PathOwnershipInfo instance. */
    constructor($$source: Partial<PathOwnershipInfo> = {}) {
        if (!("uid" in $$source)) {
            this["uid"] = "";
        }
        if (!("gid" in $$source)) {
            this["gid"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("permission" in $$source)) {
            this["permission"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathOwnershipInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PathOwnershipInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PathOwnershipInfo($$parsedSource as Partial<PathOwnershipInfo>);
    }
}

export class PortForwardInfo {
    "ID": string;
    "Kind": string;
    "Addr": string;
    "LocalAddr": string;
    "RemoteAddr": string;
    "LocalHost": string;
    "LocalPort": string;
    "RemoteHost": string;
    "RemotePort": string;
    "Enabled": boolean;

    /** Creates a new PortForwardInfo instance. */
    constructor($$source: Partial<PortForwardInfo> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Kind" in $$source)) {
            this["Kind"] = "";
        }
        if (!("Addr" in $$source)) {
            this["Addr"] = "";
        }
        if (!("LocalAddr" in $$source)) {
            this["LocalAddr"] = "";
        }
        if (!("RemoteAddr" in $$source)) {
            this["RemoteAddr"] = "";
        }
        if (!("LocalHost" in $$source)) {
            this["LocalHost"] = "";
        }
        if (!("LocalPort" in $$source)) {
            this["LocalPort"] = "";
        }
        if (!("RemoteHost" in $$source)) {
            this["RemoteHost"] = "";
        }
        if (!("RemotePort" in $$source)) {
            this["RemotePort"] = "";
        }
        if (!("Enabled" in $$source)) {
            this["Enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortForwardInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PortForwardInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortForwardInfo($$parsedSource as Partial<PortForwardInfo>);
    }
}

// Private type creation functions
const $$createType0 = OwnershipCandidateEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
