// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "./provider/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as aitypes$0 from "../aitypes/models.js";

export const AIChatCommandTerminalCandidate = aitypes$0.AIChatCommandTerminalCandidate;
export type AIChatCommandTerminalCandidate = aitypes$0.AIChatCommandTerminalCandidate;

export class AIConversationAPIMessage {
    "role": string;
    "content": string;
    "contentBlocks"?: { [_ in string]?: any }[];
    "messageId"?: string;
    "uiMessageIds"?: string[];
    "images"?: string[];
    "cacheObjects"?: AIConversationProviderCacheObjects | null;
    "ts"?: number;

    /** Creates a new AIConversationAPIMessage instance. */
    constructor($$source: Partial<AIConversationAPIMessage> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationAPIMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConversationAPIMessage {
        const $$createField2_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("contentBlocks" in $$parsedSource) {
            $$parsedSource["contentBlocks"] = $$createField2_0($$parsedSource["contentBlocks"]);
        }
        if ("uiMessageIds" in $$parsedSource) {
            $$parsedSource["uiMessageIds"] = $$createField4_0($$parsedSource["uiMessageIds"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField5_0($$parsedSource["images"]);
        }
        if ("cacheObjects" in $$parsedSource) {
            $$parsedSource["cacheObjects"] = $$createField6_0($$parsedSource["cacheObjects"]);
        }
        return new AIConversationAPIMessage($$parsedSource as Partial<AIConversationAPIMessage>);
    }
}

export class AIConversationAPIMessageTokenEntry {
    "messageId": string;
    "rawTokens": number;

    /** Creates a new AIConversationAPIMessageTokenEntry instance. */
    constructor($$source: Partial<AIConversationAPIMessageTokenEntry> = {}) {
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("rawTokens" in $$source)) {
            this["rawTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationAPIMessageTokenEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConversationAPIMessageTokenEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConversationAPIMessageTokenEntry($$parsedSource as Partial<AIConversationAPIMessageTokenEntry>);
    }
}

export class AIConversationBackup {
    "id": string;
    "ts": number;
    "message": string;
    "messageRole"?: string;
    "type": string;

    /** Creates a new AIConversationBackup instance. */
    constructor($$source: Partial<AIConversationBackup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("ts" in $$source)) {
            this["ts"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationBackup instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConversationBackup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConversationBackup($$parsedSource as Partial<AIConversationBackup>);
    }
}

export class AIConversationContextCondenseResult {
    "snapshot": AIConversationSnapshot;
    "summary": string;
    "prevContextTokens": number;
    "newContextTokens": number;

    /** Creates a new AIConversationContextCondenseResult instance. */
    constructor($$source: Partial<AIConversationContextCondenseResult> = {}) {
        if (!("snapshot" in $$source)) {
            this["snapshot"] = (new AIConversationSnapshot());
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("prevContextTokens" in $$source)) {
            this["prevContextTokens"] = 0;
        }
        if (!("newContextTokens" in $$source)) {
            this["newContextTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationContextCondenseResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConversationContextCondenseResult {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("snapshot" in $$parsedSource) {
            $$parsedSource["snapshot"] = $$createField0_0($$parsedSource["snapshot"]);
        }
        return new AIConversationContextCondenseResult($$parsedSource as Partial<AIConversationContextCondenseResult>);
    }
}

export class AIConversationContextMetrics {
    "contextTokens": number;

    /** Creates a new AIConversationContextMetrics instance. */
    constructor($$source: Partial<AIConversationContextMetrics> = {}) {
        if (!("contextTokens" in $$source)) {
            this["contextTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationContextMetrics instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConversationContextMetrics {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConversationContextMetrics($$parsedSource as Partial<AIConversationContextMetrics>);
    }
}

export class AIConversationFollowUpOption {
    "id"?: string;
    "answer"?: string;
    "mode"?: string;
    "disabled"?: boolean;
    "recommended"?: boolean;

    /** Creates a new AIConversationFollowUpOption instance. */
    constructor($$source: Partial<AIConversationFollowUpOption> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationFollowUpOption instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConversationFollowUpOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConversationFollowUpOption($$parsedSource as Partial<AIConversationFollowUpOption>);
    }
}

export class AIConversationFollowUpQuestion {
    "id"?: string;
    "text"?: string;
    "type"?: string;
    "options"?: AIConversationFollowUpOption[];

    /** Creates a new AIConversationFollowUpQuestion instance. */
    constructor($$source: Partial<AIConversationFollowUpQuestion> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationFollowUpQuestion instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConversationFollowUpQuestion {
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        return new AIConversationFollowUpQuestion($$parsedSource as Partial<AIConversationFollowUpQuestion>);
    }
}

export class AIConversationMessage {
    "id"?: string;
    "turnId"?: string;
    "kind": string;
    "text"?: string;
    "time"?: string;
    "metrics"?: string[];
    "streaming"?: boolean;
    "duration"?: string;
    "actionLabel"?: string;
    "title"?: string;
    "summary"?: string;
    "code"?: string;
    "status"?: string;
    "result"?: string;
    "remainingFileEdits"?: number;
    "purpose"?: string;
    "command"?: string;
    "output"?: string;
    "images"?: string[];
    "serverName"?: string;
    "toolName"?: string;
    "args"?: string;
    "response"?: string;
    "requestId"?: string;
    "question"?: string;
    "questions"?: AIConversationFollowUpQuestion[];
    "suggestions"?: string[];
    "extra"?: { [_ in string]?: any };

    /** Creates a new AIConversationMessage instance. */
    constructor($$source: Partial<AIConversationMessage> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConversationMessage {
        const $$createField5_0 = $$createType2;
        const $$createField18_0 = $$createType2;
        const $$createField25_0 = $$createType9;
        const $$createField26_0 = $$createType2;
        const $$createField27_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField5_0($$parsedSource["metrics"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField18_0($$parsedSource["images"]);
        }
        if ("questions" in $$parsedSource) {
            $$parsedSource["questions"] = $$createField25_0($$parsedSource["questions"]);
        }
        if ("suggestions" in $$parsedSource) {
            $$parsedSource["suggestions"] = $$createField26_0($$parsedSource["suggestions"]);
        }
        if ("extra" in $$parsedSource) {
            $$parsedSource["extra"] = $$createField27_0($$parsedSource["extra"]);
        }
        return new AIConversationMessage($$parsedSource as Partial<AIConversationMessage>);
    }
}

export class AIConversationMessageSearchResult {
    "conversationId": string;
    "conversationTitle": string;
    "messageId": string;
    "role": string;
    "snippet": string;
    "updatedAt": number;

    /** Creates a new AIConversationMessageSearchResult instance. */
    constructor($$source: Partial<AIConversationMessageSearchResult> = {}) {
        if (!("conversationId" in $$source)) {
            this["conversationId"] = "";
        }
        if (!("conversationTitle" in $$source)) {
            this["conversationTitle"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("snippet" in $$source)) {
            this["snippet"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationMessageSearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConversationMessageSearchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConversationMessageSearchResult($$parsedSource as Partial<AIConversationMessageSearchResult>);
    }
}

export class AIConversationOpenAIResponsesCacheObject {
    "responseId"?: string;
    "output"?: { [_ in string]?: any }[];
    "replayState"?: { [_ in string]?: any };
    "include"?: string[];
    "store"?: boolean;
    "capturedAt"?: number;

    /** Creates a new AIConversationOpenAIResponsesCacheObject instance. */
    constructor($$source: Partial<AIConversationOpenAIResponsesCacheObject> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationOpenAIResponsesCacheObject instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConversationOpenAIResponsesCacheObject {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("output" in $$parsedSource) {
            $$parsedSource["output"] = $$createField1_0($$parsedSource["output"]);
        }
        if ("replayState" in $$parsedSource) {
            $$parsedSource["replayState"] = $$createField2_0($$parsedSource["replayState"]);
        }
        if ("include" in $$parsedSource) {
            $$parsedSource["include"] = $$createField3_0($$parsedSource["include"]);
        }
        return new AIConversationOpenAIResponsesCacheObject($$parsedSource as Partial<AIConversationOpenAIResponsesCacheObject>);
    }
}

export class AIConversationProviderCacheObjects {
    "openaiResponses"?: AIConversationOpenAIResponsesCacheObject | null;

    /** Creates a new AIConversationProviderCacheObjects instance. */
    constructor($$source: Partial<AIConversationProviderCacheObjects> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationProviderCacheObjects instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConversationProviderCacheObjects {
        const $$createField0_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("openaiResponses" in $$parsedSource) {
            $$parsedSource["openaiResponses"] = $$createField0_0($$parsedSource["openaiResponses"]);
        }
        return new AIConversationProviderCacheObjects($$parsedSource as Partial<AIConversationProviderCacheObjects>);
    }
}

export class AIConversationSnapshot {
    "id": string;
    "title": string;
    "createdAt": number;
    "updatedAt": number;
    "status": string;
    "toolProtocol": string;
    "promptCacheBypassTimestamp"?: string;
    "parentConversationId"?: string;
    "rootConversationId"?: string;
    "relationType"?: string;
    "relationSource"?: string;
    "parentTitleSnapshot"?: string;
    "archived"?: boolean;
    "transient"?: boolean;
    "upstreamInputTokens"?: number;
    "upstreamOutputTokens"?: number;
    "messages": AIConversationMessage[];
    "apiMessages": AIConversationAPIMessage[];
    "settings": AIConversationTaskSettings;

    /** Creates a new AIConversationSnapshot instance. */
    constructor($$source: Partial<AIConversationSnapshot> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("toolProtocol" in $$source)) {
            this["toolProtocol"] = "";
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("apiMessages" in $$source)) {
            this["apiMessages"] = [];
        }
        if (!("settings" in $$source)) {
            this["settings"] = (new AIConversationTaskSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConversationSnapshot {
        const $$createField16_0 = $$createType13;
        const $$createField17_0 = $$createType15;
        const $$createField18_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField16_0($$parsedSource["messages"]);
        }
        if ("apiMessages" in $$parsedSource) {
            $$parsedSource["apiMessages"] = $$createField17_0($$parsedSource["apiMessages"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField18_0($$parsedSource["settings"]);
        }
        return new AIConversationSnapshot($$parsedSource as Partial<AIConversationSnapshot>);
    }
}

export class AIConversationSummary {
    "id": string;
    "title": string;
    "createdAt": number;
    "updatedAt": number;
    "status": string;
    "toolProtocol": string;
    "messageCount": number;
    "promptCacheBypassTimestamp"?: string;
    "parentConversationId"?: string;
    "rootConversationId"?: string;
    "relationType"?: string;
    "relationSource"?: string;
    "parentTitleSnapshot"?: string;
    "archived"?: boolean;
    "transient"?: boolean;
    "upstreamInputTokens"?: number;
    "upstreamOutputTokens"?: number;

    /** Creates a new AIConversationSummary instance. */
    constructor($$source: Partial<AIConversationSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("toolProtocol" in $$source)) {
            this["toolProtocol"] = "";
        }
        if (!("messageCount" in $$source)) {
            this["messageCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConversationSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConversationSummary($$parsedSource as Partial<AIConversationSummary>);
    }
}

export class AIConversationSummarySubtaskResult {
    "snapshot": AIConversationSnapshot;
    "continueText"?: string;

    /** Creates a new AIConversationSummarySubtaskResult instance. */
    constructor($$source: Partial<AIConversationSummarySubtaskResult> = {}) {
        if (!("snapshot" in $$source)) {
            this["snapshot"] = (new AIConversationSnapshot());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationSummarySubtaskResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConversationSummarySubtaskResult {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("snapshot" in $$parsedSource) {
            $$parsedSource["snapshot"] = $$createField0_0($$parsedSource["snapshot"]);
        }
        return new AIConversationSummarySubtaskResult($$parsedSource as Partial<AIConversationSummarySubtaskResult>);
    }
}

export class AIConversationTaskSettings {
    "currentProviderId": string;
    "autoApprovalEnabled": boolean;
    "alwaysAllowReadOnly": boolean;
    "alwaysAllowReadOnlyOutsideWorkspace": boolean;
    "alwaysAllowWrite": boolean;
    "alwaysAllowWriteOutsideWorkspace": boolean;
    "alwaysAllowWriteProtected": boolean;
    "alwaysAllowExecute": boolean;
    "executeApprovalMode": string;
    "allowedCommands"?: string[];
    "deniedCommands"?: string[];
    "alwaysAllowMcp": boolean;
    "alwaysAllowModeSwitch": boolean;
    "alwaysAllowSubtasks": boolean;
    "alwaysAllowFollowupQuestions": boolean;
    "collaborationExtraPrompt"?: string;

    /** Creates a new AIConversationTaskSettings instance. */
    constructor($$source: Partial<AIConversationTaskSettings> = {}) {
        if (!("currentProviderId" in $$source)) {
            this["currentProviderId"] = "";
        }
        if (!("autoApprovalEnabled" in $$source)) {
            this["autoApprovalEnabled"] = false;
        }
        if (!("alwaysAllowReadOnly" in $$source)) {
            this["alwaysAllowReadOnly"] = false;
        }
        if (!("alwaysAllowReadOnlyOutsideWorkspace" in $$source)) {
            this["alwaysAllowReadOnlyOutsideWorkspace"] = false;
        }
        if (!("alwaysAllowWrite" in $$source)) {
            this["alwaysAllowWrite"] = false;
        }
        if (!("alwaysAllowWriteOutsideWorkspace" in $$source)) {
            this["alwaysAllowWriteOutsideWorkspace"] = false;
        }
        if (!("alwaysAllowWriteProtected" in $$source)) {
            this["alwaysAllowWriteProtected"] = false;
        }
        if (!("alwaysAllowExecute" in $$source)) {
            this["alwaysAllowExecute"] = false;
        }
        if (!("executeApprovalMode" in $$source)) {
            this["executeApprovalMode"] = "";
        }
        if (!("alwaysAllowMcp" in $$source)) {
            this["alwaysAllowMcp"] = false;
        }
        if (!("alwaysAllowModeSwitch" in $$source)) {
            this["alwaysAllowModeSwitch"] = false;
        }
        if (!("alwaysAllowSubtasks" in $$source)) {
            this["alwaysAllowSubtasks"] = false;
        }
        if (!("alwaysAllowFollowupQuestions" in $$source)) {
            this["alwaysAllowFollowupQuestions"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationTaskSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConversationTaskSettings {
        const $$createField9_0 = $$createType2;
        const $$createField10_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowedCommands" in $$parsedSource) {
            $$parsedSource["allowedCommands"] = $$createField9_0($$parsedSource["allowedCommands"]);
        }
        if ("deniedCommands" in $$parsedSource) {
            $$parsedSource["deniedCommands"] = $$createField10_0($$parsedSource["deniedCommands"]);
        }
        return new AIConversationTaskSettings($$parsedSource as Partial<AIConversationTaskSettings>);
    }
}

export class AIConversationTokenLedger {
    "systemRawTokens": number;
    "entries": AIConversationAPIMessageTokenEntry[];
    "contextTokens": number;

    /** Creates a new AIConversationTokenLedger instance. */
    constructor($$source: Partial<AIConversationTokenLedger> = {}) {
        if (!("systemRawTokens" in $$source)) {
            this["systemRawTokens"] = 0;
        }
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("contextTokens" in $$source)) {
            this["contextTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConversationTokenLedger instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConversationTokenLedger {
        const $$createField1_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        return new AIConversationTokenLedger($$parsedSource as Partial<AIConversationTokenLedger>);
    }
}

/**
 * Types and normalization/persistence helpers live in internal/aitypes so that
 * config/sshmanager can use them without importing this package.
 */
export const AIGlobalSettings = aitypes$0.AIGlobalSettings;

/**
 * Types and normalization/persistence helpers live in internal/aitypes so that
 * config/sshmanager can use them without importing this package.
 */
export type AIGlobalSettings = aitypes$0.AIGlobalSettings;

export const AIProviderPromptCachePolicy = provider$0.ResponsesPromptCachePolicy;
export type AIProviderPromptCachePolicy = provider$0.ResponsesPromptCachePolicy;

export const AIProviderState = aitypes$0.AIProviderState;
export type AIProviderState = aitypes$0.AIProviderState;

export class AIProviderWebSearchValidationResult {
    "success": boolean;
    "message": string;
    "actualTitle"?: string;
    "rawOutput"?: string;
    "expectedTitle": string;

    /** Creates a new AIProviderWebSearchValidationResult instance. */
    constructor($$source: Partial<AIProviderWebSearchValidationResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("expectedTitle" in $$source)) {
            this["expectedTitle"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProviderWebSearchValidationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AIProviderWebSearchValidationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIProviderWebSearchValidationResult($$parsedSource as Partial<AIProviderWebSearchValidationResult>);
    }
}

/**
 * Types and normalization/persistence helpers live in internal/aitypes so that
 * config/sshmanager can use them without importing this package.
 */
export const AIProxyNode = aitypes$0.AIProxyNode;

/**
 * Types and normalization/persistence helpers live in internal/aitypes so that
 * config/sshmanager can use them without importing this package.
 */
export type AIProxyNode = aitypes$0.AIProxyNode;

export class ThemeToolRequest {
    "conversationId"?: string;
    "requestId"?: string;
    "action"?: string;
    "slot"?: string;
    "request"?: string;

    /** Creates a new ThemeToolRequest instance. */
    constructor($$source: Partial<ThemeToolRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeToolRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeToolRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeToolRequest($$parsedSource as Partial<ThemeToolRequest>);
    }
}

export class ThemeToolResult {
    "action"?: string;
    "status"?: string;
    "draftId"?: string;
    "slot"?: string;
    "sourceThemeId"?: string;
    "theme"?: { [_ in string]?: any };
    "appliedPaths"?: string[];
    "warnings"?: string[];
    "invalidPaths"?: string[];
    "suggestedPaths"?: string[];
    "fieldMap"?: { [_ in string]?: any };
    "settings"?: { [_ in string]?: any };
    "committedTheme"?: { [_ in string]?: any };
    "result"?: string;

    /** Creates a new ThemeToolResult instance. */
    constructor($$source: Partial<ThemeToolResult> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeToolResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeToolResult {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType2;
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType2;
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType0;
        const $$createField12_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("theme" in $$parsedSource) {
            $$parsedSource["theme"] = $$createField5_0($$parsedSource["theme"]);
        }
        if ("appliedPaths" in $$parsedSource) {
            $$parsedSource["appliedPaths"] = $$createField6_0($$parsedSource["appliedPaths"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField7_0($$parsedSource["warnings"]);
        }
        if ("invalidPaths" in $$parsedSource) {
            $$parsedSource["invalidPaths"] = $$createField8_0($$parsedSource["invalidPaths"]);
        }
        if ("suggestedPaths" in $$parsedSource) {
            $$parsedSource["suggestedPaths"] = $$createField9_0($$parsedSource["suggestedPaths"]);
        }
        if ("fieldMap" in $$parsedSource) {
            $$parsedSource["fieldMap"] = $$createField10_0($$parsedSource["fieldMap"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField11_0($$parsedSource["settings"]);
        }
        if ("committedTheme" in $$parsedSource) {
            $$parsedSource["committedTheme"] = $$createField12_0($$parsedSource["committedTheme"]);
        }
        return new ThemeToolResult($$parsedSource as Partial<ThemeToolResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = AIConversationProviderCacheObjects.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = AIConversationSnapshot.createFrom;
const $$createType6 = AIConversationFollowUpOption.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = AIConversationFollowUpQuestion.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = AIConversationOpenAIResponsesCacheObject.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = AIConversationMessage.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = AIConversationAPIMessage.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = AIConversationTaskSettings.createFrom;
const $$createType17 = AIConversationAPIMessageTokenEntry.createFrom;
const $$createType18 = $Create.Array($$createType17);
