// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ConnectedSession {
    "session_id": string;
    "group_session_id"?: string;
    "connection_ref": string;
    "connection_id"?: string;

    /**
     * Address 是 user@host:port 形式的服务器地址，用于区分同名服务器。
     */
    "address"?: string;
    "tags"?: string[];
    "sftp_available": boolean;
    "is_child_terminal": boolean;

    /** Creates a new ConnectedSession instance. */
    constructor($$source: Partial<ConnectedSession> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("connection_ref" in $$source)) {
            this["connection_ref"] = "";
        }
        if (!("sftp_available" in $$source)) {
            this["sftp_available"] = false;
        }
        if (!("is_child_terminal" in $$source)) {
            this["is_child_terminal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectedSession instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectedSession {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        return new ConnectedSession($$parsedSource as Partial<ConnectedSession>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
