// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ProgramFontInfo 描述一个已安装的程序内置字体。
 */
export class ProgramFontInfo {
    "fileName": string;
    "displayName": string;
    "source": string;
    "size": number;
    "updatedAt": number;
    "mimeType": string;

    /** Creates a new ProgramFontInfo instance. */
    constructor($$source: Partial<ProgramFontInfo> = {}) {
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProgramFontInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProgramFontInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProgramFontInfo($$parsedSource as Partial<ProgramFontInfo>);
    }
}
