// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ServerErrorEntry {
    "message": string;
    "timestamp": number;
    "level": string;

    /** Creates a new ServerErrorEntry instance. */
    constructor($$source: Partial<ServerErrorEntry> = {}) {
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerErrorEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerErrorEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerErrorEntry($$parsedSource as Partial<ServerErrorEntry>);
    }
}

export class ServerResource {
    "uri": string;
    "name": string;
    "mimeType"?: string;
    "description"?: string;

    /** Creates a new ServerResource instance. */
    constructor($$source: Partial<ServerResource> = {}) {
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerResource instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerResource {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerResource($$parsedSource as Partial<ServerResource>);
    }
}

export class ServerResourceTemplate {
    "uriTemplate": string;
    "name": string;
    "description"?: string;
    "mimeType"?: string;

    /** Creates a new ServerResourceTemplate instance. */
    constructor($$source: Partial<ServerResourceTemplate> = {}) {
        if (!("uriTemplate" in $$source)) {
            this["uriTemplate"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerResourceTemplate instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerResourceTemplate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerResourceTemplate($$parsedSource as Partial<ServerResourceTemplate>);
    }
}

export class ServerRuntime {
    "name": string;
    "config": string;
    "status": string;
    "error"?: string;
    "errorHistory"?: ServerErrorEntry[];
    "tools"?: ServerTool[];
    "resources"?: ServerResource[];
    "resourceTemplates"?: ServerResourceTemplate[];
    "disabled"?: boolean;
    "disabledForPrompts"?: boolean;
    "timeout"?: number;
    "source"?: ServerSource;
    "instructions"?: string;

    /** Creates a new ServerRuntime instance. */
    constructor($$source: Partial<ServerRuntime> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerRuntime instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerRuntime {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errorHistory" in $$parsedSource) {
            $$parsedSource["errorHistory"] = $$createField4_0($$parsedSource["errorHistory"]);
        }
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField5_0($$parsedSource["tools"]);
        }
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField6_0($$parsedSource["resources"]);
        }
        if ("resourceTemplates" in $$parsedSource) {
            $$parsedSource["resourceTemplates"] = $$createField7_0($$parsedSource["resourceTemplates"]);
        }
        return new ServerRuntime($$parsedSource as Partial<ServerRuntime>);
    }
}

export enum ServerSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ServerSourceEmbedded = "embedded",
    ServerSourceGlobal = "global",
};

export class ServerTool {
    "name": string;
    "description"?: string;
    "inputSchema"?: { [_ in string]?: any };
    "alwaysAllow"?: boolean;
    "enabledForPrompt"?: boolean;

    /** Creates a new ServerTool instance. */
    constructor($$source: Partial<ServerTool> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerTool instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerTool {
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inputSchema" in $$parsedSource) {
            $$parsedSource["inputSchema"] = $$createField2_0($$parsedSource["inputSchema"]);
        }
        return new ServerTool($$parsedSource as Partial<ServerTool>);
    }
}

// Private type creation functions
const $$createType0 = ServerErrorEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ServerTool.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ServerResource.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ServerResourceTemplate.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
